name: Building MacOS package
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: macos-10.15
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Init venv
        run: |
          python -m venv venv3
          source venv3/bin/activate
          pip install --upgrade pip
      - name: Build and install backend package
        run: |
          pip install ${{ github.workspace }}/backend
