name: Building MacOS package
on: [push]
jobs:
  Build-Package:
    runs-on: macos-10.15
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Init venv
        run: |
          python -m venv ${{ github.workspace }}/.venv3
          source ${{ github.workspace }}/.venv3/bin/activate
          pip install --upgrade pip wheel setuptools
      - name: Install the backend Python package
        run: |
          source ${{ github.workspace }}/.venv3/bin/activate
          pip install ${{ github.workspace }}/backend[dev]
      - name: Build PyInstaller-based binary
        run: |
          source ${{ github.workspace }}/.venv3/bin/activate
          cd ${{ github.workspace }}/backend
          pyinstaller ./backend.spec
      - name: Build Electron app
        run: |
          cd ${{ github.workspace }}/app
          npm ci
          npm run electron:package
      - name: Archive the built app
        uses: actions/upload-artifact@v2
        with:
          name: simpledam_dmg_package
          path: ${{ github.workspace }}/app/dist_electron/*.dmg
          if-no-files-found: error
          retention-days: 7
